# Generated by Django 2.2.12 on 2020-04-24 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verifies',
            new_name='is_verified',
        ),
    ]
