# Generated by Django 2.2.12 on 2020-04-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0003_auto_20200424_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20, verbose_name='password'),
        ),
    ]
