# Generated by Django 2.2.12 on 2020-04-25 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('plot', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=25, verbose_name='content type')),
            ],
            options={
                'verbose_name_plural': 'contents',
                'verbose_name': 'content',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='genre')),
            ],
        ),
        migrations.CreateModel(
            name='ContentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb', models.ImageField(blank=True, db_column='thumb_image', null=True, upload_to='uploads/content/thumb/', verbose_name='thumb image')),
                ('type', models.CharField(max_length=25, verbose_name='image type')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', related_query_name='content', to='movies.Content')),
            ],
            options={
                'verbose_name_plural': 'contentimages',
                'verbose_name': 'contentimage',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='genres',
            field=models.ManyToManyField(related_name='genres', related_query_name='genre', to='movies.Genre'),
        ),
    ]
