# Generated by Django 2.2.12 on 2020-04-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('Movie', 'Movie'), ('WebSeries', 'WebSeries'), ('DailyShop', 'DailyShop')], max_length=25, verbose_name='content type'),
        ),
    ]
