# Generated by Django 2.2.12 on 2020-04-25 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200425_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentimage',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', related_query_name='image', to='movies.Content'),
        ),
    ]
