# Generated by Django 2.2.12 on 2020-04-29 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20200425_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='added_date',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='content',
            name='date_of_release',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentimage',
            name='added_date',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='genre',
            name='added_date',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
