# Generated by Django 2.2.12 on 2020-04-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20200429_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentimage',
            name='type',
            field=models.CharField(choices=[('THUMB', 'Thumb'), ('LARGE', 'Large'), ('BANNER', 'Banner')], max_length=25, verbose_name='image type'),
        ),
    ]
